[versions]
agp = "8.7.2"
#kotlin = "2.2.20"
#coreKtx = "1.17.0"
#junitVersion = "1.3.0"
#espressoCore = "3.7.0"
#activityCompose = "1.10.1"
#composeBom = "2024.09.00"
#navigationCompose = "2.8.9"
#hiltNavigationCompose = "1.2.0"
#hilt = "2.55"
#ksp = "2.1.0+"
#kotlinx-serialization = "1.9.0"
#agp = "8.7.3"
kotlin = "2.1.10"
coreKtx = "1.15.0"
activityCompose = "1.10.1"
composeBom = "2025.03.00"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
navigationCompose = "2.8.9"
compose-coil = "2.7.0"
kotlinx-serialization = "1.7.3"
timber = "5.0.1"
hilt = "2.55"
hiltNavigationCompose = "1.2.0"
ksp = "2.1.0+"
kotlinx-collections-immutable = "0.3.7"
jupiter = "5.10.3"
kotlinx = "1.9.0"
junit = "4.13.2"
lifecycleRuntimeKtx = "2.9.3"
coil_bom = "3.0.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

coil-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil_bom" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp" }
coil-network-cache = { module = "io.coil-kt.coil3:coil-network-cache-control" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]
coil-compose = ["coil-compose","coil-network", "coil-network-cache", "coil-svg"]
